file_type: csv
dataset_name: ecommerce_data
file_name: 2019-Oct
table_name: ecommerce_transactions
inbound_delimiter: ","
outbound_delimiter: "|"
skip_leading_rows: 0
columns:
    - event_time
    - event_type
    - product_id
    - category_id
    - category_code
    - brand
    - price
    - user_id
    - user_session
